#### MAKEFILE
#### Generated by myself.

#### Currently support two platforms:
####  - MacOS
####  - Windows

## Compiler settings.
CC     := g++
CLANG  := clang++
CFLAGS := -std=c++17 # -Og -Wall -Wextra
## Basic settings.
TARGET   := viewer
BUILDDIR := build
ICDDIR   := include
SRCDIR   := src
## Add your *.cpp file here, make sure they are under SRCDIR folder.
SOURCES  := main.cpp
INCLUDES := $(wildcard $(addprefix $(ICDDIR)/, *.h))
OBJECTS  := $(addprefix $(BUILDDIR)/, $(notdir $(SOURCES:.cpp=.o)))

ifeq ($(OS),Windows_NT)
	MKDIR    := if not exist $(BUILDDIR) mkdir $(BUILDDIR)
	RUN      :=
	PLATFORM := win32
else
    UNAME_S := $(shell uname -s)
    ifeq ($(UNAME_S),Darwin)
		MKDIR    := mkdir -p $(BUILDDIR)
		RUN      := ./
		PLATFORM := macos
		CLEAN    := rm -rf $(BUILDDIR)
    endif
endif

all: $(PLATFORM)

prepare:
	@$(MKDIR)

macos: prepare $(OBJECTS)
	@$(CLANG) -o $(TARGET) -framework Cocoa $(CFLAGS) platform/macos.mm $(OBJECTS)

$(BUILDDIR)/%.o: $(SRCDIR)/%.cpp
	@$(CC) $(CFLAGS) -o $@ -c $<

clean:
	@$(CLEAN)

run: $(PLATFORM)
	@$(RUN)$(TARGET)

